[package]
name = "sagevault"
version = "0.1.0"
edition = "2024"

# 패키지는 sagevault, 실행 명령은 짧게 sgv
[[bin]]
name = "sgv"
path = "src/main.rs"

[dependencies]
argon2 = { version = "0.6.0", default-features = false, features = ["alloc", "zeroize"] }
blake2 = { version = "0.11", features = ["zeroize"] }
chacha20poly1305 = { version = "0.11.0", features = ["alloc", "zeroize"] }
getrandom = "0.4"
libc = "0.2.189"
rpassword = "7.5.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
zeroize = { version = "1.9.0", features = ["serde"] }

# 가벼운 단일 바이너리
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

# 디버그 빌드에서도 KDF가 느리지 않게
[profile.dev.package.argon2]
opt-level = 3
[profile.dev.package.blake2]
opt-level = 3
